version: "2.1"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID= 20
      - MYSQL_ROOT_PASSWORD=password
      - TZ=America/Los_Angeles

    volumes:
      - ./db:/config

    restart: unless-stopped

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    image: baseball
    volumes:
      - "./mystuff:/app/mystuff"
